# Generated by Django 3.2.9 on 2021-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0004_auto_20211219_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='flight',
            field=models.ManyToManyField(default=1, to='booksystem.Flight'),
        ),
    ]
